repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: validate_placements
        name: validate_placements
        entry: python scripts/validate_placements.py
        language: system
        pass_filenames: true

      - id: run-pytest
        name: run-pytest
        entry: python -m pytest tests
        language: system
        pass_filenames: false
